apiVersion: v1
kind: Service
metadata:
  name: auto-deployment
  namespace: namespace-workflow-1739433082531
  labels:
    app.kubernetes.io/name: auto-deployment
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: auto-deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000